baseURL = "/"
languageCode = "en-us"
title = "iotsmesh"
theme = "kube"
description = "Building IoT platform based on Service Mesh"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "iotsmesh" # add your company name
  github = "https://github.com/guojerry" # add your github profile name
  twitter = "" # add your twitter profile
  email = "guofei75@gmail.com"

#[[menu.main]]
#    name = "Docs"
#    weight = -100
#    url = "/docs/"
#[[menu.main]]
#    name = "Blog"
#    weight = -100
#    url = "/blog/"
#[[menu.main]]
#    name = "Faq"
#    weight = -100
#    url = "/faq/"
