# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "iotsmesh"
license = "Apache-2.0"
licenselink = "https://github.com/iotsmesh/iotsmesh/blob/master/LICENSE"
description = "Build IoT platform with Service Mesh Technology"
homepage = "http://iotsmesh.io/"
tags = ["responsive", "kube", "documentation", "landing", "blog", "themes", "professional", "modern"]
features = ["Minimalism","Mobile-first Design",
  "Responsive Design",
  "Horizontal Rhythm",
  "Typography",
  "Google Analytics",
  "Disqus Commenting",
  "OpenGraph support",
  "Schema Structured Data",
  "Paginated Lists",
  "Reading Time",
  "Last Modified time",
  "Word Count",
  "Related Posts",
  "Block Templates",
  "Table of Contents",
  "SEO Site Verification"]
min_version = 0.19

[author]
  name = "Fei Guo"
  homepage = "https://github.com/guojerry"
 
